version: '3.8' # Or your preferred version

services:
  web:
    build: . 
    container_name: rule4local 
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000" 
    env_file:
      - .env      
    environment:
      - PYTHONUNBUFFERED=1 
      - DJANGO_SETTINGS_MODULE=rule4be.settings 
