# Generated by Django 4.2.7 on 2024-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0002_alter_snapshot_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='snapshots/'),
        ),
    ]
