# Generated by Django 4.2.7 on 2024-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0003_snapshot_image_snapshot_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snapshot-images/'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='snapshot-videos/'),
        ),
    ]
