# Generated by Django 4.2.7 on 2024-11-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0005_alter_snapshot_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaoflife',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
