name: Build and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - rule4-k8s

env:
  IMAGE_NAME: rule4

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: # Needed for Workload Identity Federation
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Authentication to GCP ---
      - name: Authenticate to Google Cloud (SA Key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # # --- Fetch Secret from GCP Secret Manager ---
      # - name: Get DATABASE_URL from Secret Manager
      #   id: db_url_secret # Give it an ID to reference its outputs
      #   uses: google-github-actions/get-secretmanager-secrets@v2
      #   with:
      #     secrets: |- # Use |- for multi-line input if fetching multiple secrets
      #       DB_URL_FROM_GCP:${{ secrets.GCP_DB_URL_SECRET_NAME }}
      #       AWS_ACCESS_KEY_ID_FROM_GCP:${{ secrets.GCP_AWS_ACCESS_KEY_ID }}
      #       AWS_SECRET_ACCESS_KEY_FROM_GCP:${{ secrets.GCP_AWS_SECRET_ACCESS_KEY }}
      #       AWS_STORAGE_BUCKET_NAME_FROM_GCP:${{ secrets.GCP_AWS_STORAGE_BUCKET_NAME }}
      #       AWS_S3_REGION_NAME_FROM_GCP:${{ secrets.GCP_AWS_S3_REGION_NAME }}
      #       AWS_S3_CUSTOM_DOMAIN_FROM_GCP:${{ secrets.GCP_AWS_S3_CUSTOM_DOMAIN }}
      #       AWS_CLOUDFRONT_KEY_ID_FROM_GCP:${{ secrets.GCP_AWS_CLOUDFRONT_KEY_ID }}
      #       AWS_CLOUDFRONT_KEY_FROM_GCP:${{ secrets.GCP_AWS_CLOUDFRONT_KEY }}


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix= # Git commit SHA as tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/rule4-k8s' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Enable GitHub Actions cache for Docker layers
          cache-to: type=gha,mode=max # Write to GitHub Actions cache
          # build-args: | 
          #   DATABASE_URL_ARG=${{ steps.db_url_secret.outputs.DB_URL_FROM_GCP }}
          #   AWS_ACCESS_KEY_ID_ARG=${{ steps.db_url_secret.outputs.AWS_ACCESS_KEY_ID_FROM_GCP }}
          #   AWS_SECRET_ACCESS_KEY_ARG=${{ steps.db_url_secret.outputs.AWS_SECRET_ACCESS_KEY_FROM_GCP }}
          #   AWS_STORAGE_BUCKET_NAME_ARG=${{ steps.db_url_secret.outputs.AWS_STORAGE_BUCKET_NAME_FROM_GCP }}
          #   AWS_S3_REGION_NAME_ARG=${{ steps.db_url_secret.outputs.AWS_S3_REGION_NAME_FROM_GCP }}
          #   AWS_S3_CUSTOM_DOMAIN_ARG=${{ steps.db_url_secret.outputs.AWS_S3_CUSTOM_DOMAIN_FROM_GCP }}
          #   AWS_CLOUDFRONT_KEY_ID_ARG=${{ steps.db_url_secret.outputs.AWS_CLOUDFRONT_KEY_ID_FROM_GCP }}
          #   AWS_CLOUDFRONT_KEY_ARG=${{ steps.db_url_secret.outputs.AWS_CLOUDFRONT_KEY_FROM_GCP }}

      - name: Print Image URL
        run: |
          echo "Image pushed to:"
          echo "${{ steps.meta.outputs.tags }}"