name: Build and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - rule4-k8s

env:
  IMAGE_NAME: rule4

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: # Needed for Workload Identity Federation
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Authentication to GCP ---
      - name: Authenticate to Google Cloud (SA Key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix= # Git commit SHA as tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/rule4-k8s' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Enable GitHub Actions cache for Docker layers
          cache-to: type=gha,mode=max # Write to GitHub Actions cache

      - name: Print Image URL
        run: |
          echo "Image pushed to:"
          echo "${{ steps.meta.outputs.tags }}"